# Generated by Django 6.0.2 on 2026-02-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.businesstype'),
        ),
    ]
