# Generated by Django 6.0.2 on 2026-02-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='code',
            field=models.CharField(choices=[('pizzeria', 'Pizzeria'), ('heladeria', 'Heladeria'), ('restaurante', 'Restaurante'), ('cafeteria', 'Cafeteria'), ('panaderia', 'Panaderia'), ('bar', 'Bar/Pub'), ('comida_rapida', 'Comida Rapida')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='default_categories',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='default_products',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='default_roles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('manager', 'Encargado'), ('employee', 'Empleado'), ('cashier', 'Cajero'), ('cook', 'Cocinero'), ('delivery', 'Delivery')], default='employee', max_length=20),
        ),
    ]
