# Generated by Django 6.0.2 on 2026-02-24 12:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Backups activados')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('every_12h', 'Cada 12 horas'), ('every_6h', 'Cada 6 horas'), ('weekly', 'Semanal')], default='daily', max_length=20, verbose_name='Frecuencia')),
                ('backup_time', models.TimeField(default=datetime.time(3, 0), verbose_name='Hora del backup')),
                ('backup_dir', models.CharField(blank=True, default='', max_length=500, verbose_name='Carpeta de backups')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='Dias de retencion')),
                ('max_backups', models.PositiveIntegerField(default=50, verbose_name='Maximo de backups')),
                ('compress', models.BooleanField(default=True, verbose_name='Comprimir backups')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo backup')),
                ('last_backup_status', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion de Backups',
                'verbose_name_plural': 'Configuracion de Backups',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Archivo')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta completa')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamano (bytes)')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('in_progress', 'En progreso')], default='in_progress', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Programado')], default='manual', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('duration_seconds', models.FloatField(default=0, verbose_name='Duracion (seg)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Registro de Backup',
                'verbose_name_plural': 'Registros de Backup',
                'ordering': ['-created_at'],
            },
        ),
    ]
