# Generated by Django 6.0.2 on 2026-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_type',
            field=models.CharField(choices=[('local', 'Local'), ('takeaway', 'Para Llevar'), ('delivery', 'Delivery')], default='local', max_length=20),
        ),
    ]
