# Generated by Django 6.0.2 on 2026-02-23 22:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icono CSS/emoji', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Color hex', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Precio base del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('has_variants', models.BooleanField(default=False, help_text='¿Tiene variantes? (tamaños, sabores, etc.)')),
                ('is_combo', models.BooleanField(default=False, help_text='¿Es un combo de productos?')),
                ('requires_preparation', models.BooleanField(default=True, help_text='¿Requiere preparación en cocina?')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('track_inventory', models.BooleanField(default=False)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['category', 'sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_optional', models.BooleanField(default=False)),
                ('combo_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='products.product')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_combos', to='products.product')),
            ],
            options={
                'verbose_name': 'Componente de Combo',
                'verbose_name_plural': 'Componentes de Combo',
                'unique_together': {('combo_product', 'component_product')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('size', 'Tamaño'), ('flavor', 'Sabor'), ('topping', 'Extra/Topping'), ('preparation', 'Preparación'), ('custom', 'Personalizado')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Modificador de precio (+/- respecto al precio base)', max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['variant_type', 'sort_order', 'name'],
                'unique_together': {('product', 'variant_type', 'name')},
            },
        ),
    ]
